#!/usr/bin/env python

'''
Defines and trains FwLM-GNN model for PANDA Barrel DIRC.

Run from CLI:
python panda_fwlmgnn.py -i dataset/ -o models
'''

from importlib.resources import path

import torch
import subprocess

torch.multiprocessing.set_sharing_strategy('file_system')
torch.set_float32_matmul_precision('high')
torch._dynamo.config.capture_scalar_outputs = True

# ----- MLP Layer ----- #

import torch.nn as nn
from torch_geometric.nn import MessagePassing

class PandaGNNLayer(MessagePassing):
    def __init__(self, node_dim, edge_dim, hidden_dim, mlp_layers=1, mlp_dim=64):
        super().__init__(aggr='add')    # Sum aggregation; other options include 'mean' and 'max'
    
        # MLP encoder for edges 
        self.edge_mlp = self.build_mlp(
            input_dim   = 2*node_dim + edge_dim, 
            hidden_dim  = mlp_dim, 
            output_dim  = hidden_dim, 
            n_layers    = mlp_layers
        )
        
        # MLP encoder for nodes
        self.node_mlp = self.build_mlp(
            input_dim   = node_dim + hidden_dim, 
            hidden_dim  = mlp_dim, 
            output_dim  = hidden_dim, 
            n_layers    = mlp_layers
        )
    
    def forward(self, x, edge_index, edge_attr):
        return self.propagate(x=x, edge_index=edge_index, edge_attr=edge_attr)
    
    def message(self, x_i, x_j, edge_attr):
        # x_i = reciever node
        # x_j = sender node
        
        m = torch.cat([x_i, x_j, edge_attr], dim=-1)
        return self.edge_mlp(m)
    
    def update(self, aggr_out, x):
        # aggr_out = sum of incoming messages
        
        h = torch.cat([x, aggr_out], dim=-1)
        return self.node_mlp(h)
    
    @staticmethod
    def build_mlp(input_dim, hidden_dim, output_dim, n_layers):
        '''
        Helper function to build an MLP with given dimensions and number of ReLU-activated hidden layers.
        '''
        
        layers = []
        
        layers.append(nn.Linear(input_dim, hidden_dim))
        layers.append(nn.ReLU())
        
        for _ in range(n_layers - 1):
            layers.append(nn.Linear(hidden_dim, hidden_dim))
            layers.append(nn.ReLU())
            
        
        layers.append(nn.Linear(hidden_dim, output_dim))
        
        return nn.Sequential(*layers)



# ----- Model Architecture Definition ----- #

from torch_geometric.nn import global_mean_pool

class PandaGNN(nn.Module):
    def __init__(self, node_dim, edge_dim, global_dim, hidden_dim, n_classes, mlp_layers=1, mlp_dim=64, gnn_layers=2):
        super().__init__()
        
        self.num_gnn_layers = gnn_layers
        
        self.node_dim = node_dim
        self.edge_dim = edge_dim
        self.global_dim = global_dim
        self.hidden_dim = hidden_dim
        self.n_classes = n_classes
        self.mlp_layers = mlp_layers
        self.mlp_dim = mlp_dim

        self.gnn_layers = nn.ModuleList()
        
        for _ in range(gnn_layers):
            self.gnn_layers.append(PandaGNNLayer(node_dim if _ == 0 else hidden_dim, edge_dim, hidden_dim, mlp_layers, mlp_dim))

        
        self.fwlm = nn.Linear(global_dim, 2 * hidden_dim) # FiLM layer to modulate pooled node features with global features
        
        self.classifier = PandaGNNLayer.build_mlp(
            input_dim   = hidden_dim,
            hidden_dim  = hidden_dim,
            output_dim  = n_classes,
            n_layers    = mlp_layers
        )
    
    def forward(self, data):
        x = data.x
        edge_index = data.edge_index
        edge_attr = data.edge_attr
        batch = data.batch
        
        for gnn in self.gnn_layers:
            x = gnn(x, edge_index, edge_attr)
            x = torch.relu(x)
        
        # Pooling
        x = global_mean_pool(x, batch)
        g = data.global_features
        g = g.view(data.num_graphs, -1) # reshape because PyTorch batching concatenates global features lazily, not per graph
        
        gamma, beta = self.fwlm(g).chunk(2, dim=-1)
        
        x = gamma * x + beta
        
        return self.classifier(x)


# ----- Lazy Data Batch Loader ----- #

'''
Expects .pkl files like this:

input/
├─ batch_1.pkl
├─ batch_2.pkl
├─ batch_3.pkl
├─ batch_4.pkl
├─ .....

where the .pkl files are generated by convert_gnn.py. This folder needs to be clean, i.e no other file types inside.
'''

from torch.utils.data import Dataset
from torch_geometric.data import Data
import pickle, json
import os
import tqdm
from collections import OrderedDict

class PandaGNNDataset(Dataset):
    def __init__(self, folder, cache_size=5, nevents=None):
        
        '''
        Cache; NOT IMPLEMENTED
        '''
        
        
        self.files = sorted([
            os.path.join(folder, f)
            for f in os.listdir(folder)
            if f.endswith(".pkl")
        ])
        
        # Build index: (file_id, event_id)
        self.index = []
        total = 0
        
        print(f'[INFO] Counting events in each file to build index...')
        
        data_bar = tqdm.tqdm(enumerate(self.files), total=len(self.files), desc='Building dataset index')

        for file_id, file in data_bar:
            
            header_file = file.replace('.pkl', '_header.json')
            
            with open(header_file, 'rb') as f:
                header = json.load(f)
            
            n_file_events = header['nevents']
            
            if nevents is None:
                
                for i in range(n_file_events):
                    self.index.append((file_id, i))
            else:
                
                remaining = nevents - total
                if remaining <= 0:
                    break
                
                take = min(remaining, n_file_events)
                
                for i in range(take):
                    self.index.append((file_id, i))
                
                total += take
        
        self.cache_size = cache_size
        
        self._current_file_id = None
        self._current_data = None
    
    def __len__(self):
        return len(self.index)
    
    def load_file(self, file_id):
        if self._current_file_id != file_id:
            with open(self.files[file_id], 'rb') as f:
                self._current_data = pickle.load(f)
            self._current_file_id = file_id
    
    def __getitem__(self, idx):
        file_id, event_id = self.index[idx]
        
        self.load_file(file_id)
        data = self._current_data
        
        x           = torch.tensor(data['nodes'][event_id],         dtype=torch.float)
        edge_index  = torch.tensor(data['edges'][event_id].T,       dtype=torch.long)
        edge_attr   = torch.tensor(data['edge_features'][event_id], dtype=torch.float)
        y           = torch.tensor([data['labels'][event_id]],      dtype=torch.long)
        g           = torch.tensor(data['globals'][event_id],       dtype=torch.float)
        
        # Reshapes in case the event was empty for whatever reason, to ensure correct dimensions for batching
        if edge_index.numel() == 0:
            edge_index = torch.empty((2, 0), dtype=torch.long)
        
        if edge_attr.numel() == 0:
            edge_attr = torch.empty((0, 3), dtype=torch.float)
        
        graph = Data(x=x, edge_index=edge_index, edge_attr=edge_attr, y=y)
        graph.global_features = g
        
        return graph


def batch_diagnostics(batch):
    print(batch.x.dtype)
    print(batch.edge_index.dtype)
    print(batch.edge_attr.dtype)
    
    print(batch.edge_index.min())
    print(batch.edge_index.max())
    
    print(batch.x.shape)

# ----- Main ----- #

if __name__ == "__main__":

    # ----- CLI ----- #
    
    import argparse
    
    parser = argparse.ArgumentParser(prog='panda_gnn', description='Defines and trains GNN model for PANDA Barrel DIRC.')
    
    parser.add_argument('-i', '--input', type=str, required=True, help='Path to input pickle file\\s.')
    parser.add_argument('-o', '--output', type=str, required=False, default='tmp', help='Path to output model file.')
    parser.add_argument('-batch-size', '--batch-size', type=int, default=64, help='Data batch size for training.')
    parser.add_argument('--batch', action='store_true', help='Load .pkl inputs in batch mode (0) or single file mode (1).')
    parser.add_argument('-nevents', '--nevents', type=int, default=None, help='Number of events to load from each .pkl file.')
    parser.add_argument('-nepochs', '--nepochs', type=int, default=20, help='Number of training epochs.')
    parser.add_argument('--verbose', action='store_true', help='Print verbose output during training.')
    parser.add_argument('-mlp-layers', '--mlp-layers', type=int, default=1, help='Number of layers in MLPs within GNN. Default: 1')
    parser.add_argument('-mlp-dim', '--mlp-dim', type=int, default=64, help='Hidden dimension of MLPs within GNN. Default: 64')
    parser.add_argument('-gnn-layers', '--gnn-layers', type=int, default=2, help='Number of GNN layers in the model. Default: 2')
    parser.add_argument('-global-dim', '--global-dim', type=int, default=8, help='Dimension of global features. Default: 8')
    parser.add_argument('--compile', action='store_true', help='Compile the model with torch.compile for faster training (may cause issues on some platforms).')
    
    args = parser.parse_args()
    
    # ----- Load (Single File Mode) ----- #
    
    from torch_geometric.loader import DataLoader
    import torch.nn.functional as F
    
    if not args.batch:
        print('[INFO] Running in single .pkl file mode')
        with open(args.input, "rb") as f:
            data = pickle.load(f)
        
        nevents = len(data['labels'])
        
        dataset = []
        
        for i in range(nevents):
            x           = torch.tensor(data['nodes'][i], dtype=torch.float)
            edge_index  = torch.tensor(data['edges'][i].T, dtype=torch.long)
            edge_attr   = torch.tensor(data['edge_features'][i], dtype=torch.float)
            y   = torch.tensor([data['labels'][i]], dtype=torch.long)
            g   = torch.tensor(data['globals'][i], dtype=torch.float) 
            
            graph = Data(x=x, edge_index=edge_index, edge_attr=edge_attr, y=y)
            graph.global_features = g
            
            dataset.append(graph)
        
        loader = DataLoader(dataset, batch_size=args.batch_size, shuffle=True)
    
    # ----- Load (Batch File Mode) ----- #
    
    if args.batch:
        print('[INFO] Running in batch .pkl file mode')
        dataset = PandaGNNDataset(args.input, nevents=args.nevents)
        print(f'[INFO] Dataset class initialised with {len(dataset)} events across {len(dataset.files)} files. Cache size: {dataset.cache_size} files.')
        loader = DataLoader(dataset, batch_size=args.batch_size, shuffle=False, num_workers=2, prefetch_factor=1, persistent_workers=True, pin_memory=True)
        print(f'[INFO] DataLoader initialised with batch size {args.batch_size}.')
    
    # ----- Training Loop ----- #
    # -----      Save     ----- #
    
    import datetime, time
    
    n = 1
    while True:
        outdir = f"models/{args.output}_{n}__{datetime.date.today().strftime('%Y-%m-%d')}"
        if not os.path.exists(outdir):
            break
        n += 1
    
    subprocess.run(f"mkdir -p {outdir}", shell=True)
    
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    
    model = PandaGNN(node_dim=3, edge_dim=3, global_dim=args.global_dim, hidden_dim=64, n_classes=2, mlp_layers=args.mlp_layers, mlp_dim=args.mlp_dim, gnn_layers=args.gnn_layers)
    model.to(device)
    
    if args.compile: model = torch.compile(model)
    
    optimiser = torch.optim.Adam(model.parameters(), lr=1e-3)
    
    print(f'[INFO] Starting training on device: {device}')
    
    model.train()
    
    for epoch in range(args.nepochs):
        total_loss = 0
        total_samples = 0
        
        pbar = tqdm.tqdm(loader, desc=f'Epoch {epoch}')
        prev_time = time.time()
        
        for batch in pbar:
            
            batch = batch.to(device)
            
            now = time.time()
            data_time = now - prev_time
            t1 = time.time()       
            
            # ----- Compute ----- #
            
            optimiser.zero_grad()
            
            out = model(batch)
            
            loss = F.cross_entropy(out, batch.y.view(-1), reduction='sum')
            
            loss.backward()
            optimiser.step()
            
            total_loss += loss.item()
            total_samples += batch.y.view(-1).size(0)
            
            # -----   ...   ----- #
            
            t2 = time.time()
            pbar.set_postfix({
                'load': f"{data_time:.2f}s",
                'compute': f"{(t2 - t1):.2f}s"
            })
            
            prev_time = time.time()
        
        epoch_loss = total_loss / total_samples
        
        print(f'Epoch {epoch}, Loss: {epoch_loss:.4f}')
        
        checkpoint = {
            "model_state_dict": model.state_dict(),
            
            "optimiser_state_dict": optimiser.state_dict(),

            "model_config": {
                "node_dim": model.node_dim,
                "edge_dim": model.edge_dim,
                "global_dim": model.global_dim,
                "hidden_dim": model.hidden_dim,
                "n_classes": model.n_classes,
                "mlp_layers": model.mlp_layers,
                "mlp_dim": model.mlp_dim,
                "gnn_layers": model.num_gnn_layers,
            },
            
            "args": vars(args),
            
            "epoch": epoch,
            "train_loss": epoch_loss,
            "batch_size": loader.batch_size,
            "num_events": len(dataset),
        }

        torch.save(checkpoint, f"{outdir}/weights__epoch-{epoch}__loss-{epoch_loss:.4f}.pt")
    
    with open(f"{outdir}/run_info.txt", "w") as f:
        f.write(str(model))
        f.write("\n\n")

        f.write(f"Batch size: {loader.batch_size}\n")
        f.write(f"Num events: {len(dataset)}\n")

